'use client';
import Image from 'next/image';
import { useState } from 'react';
type Photo = { id:string; filename:string; url?:string; is_cover:boolean; processing_status:string };
export function GalleryPhotos({ galleryId, photos: initialPhotos }: { galleryId: string; photos: Photo[] }) {
  const [photos, setPhotos] = useState(initialPhotos); const [busy, setBusy] = useState<string | null>(null); const [status, setStatus] = useState('');
  async function setCover(photoId: string) { setBusy(photoId); setStatus(''); const response = await fetch('/api/admin/gallery-cover', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ galleryId, photoId }) }); const result = await response.json(); if (response.ok) { setPhotos(current => current.map(photo => ({ ...photo, is_cover: photo.id === photoId }))); setStatus('Capa da galeria atualizada.'); } else setStatus(`Erro: ${result.error ?? 'Não foi possível atualizar a capa.'}`); setBusy(null); }
  return <section className="mt-10"><p className="text-xs uppercase tracking-[0.2em] text-gold">Fotos carregadas</p><h2 className="mt-3 font-display text-3xl">{photos.length} fotografia(s) na galeria</h2>{status&&<p role="status" className="mt-4 text-sm text-emerald-300">{status}</p>}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{photos.map(photo=><figure key={photo.id} className="border border-white/10 bg-surface p-3">{photo.url&&<Image src={photo.url} alt={photo.filename} width={800} height={600} className="aspect-[4/3] object-cover" unoptimized />}<figcaption className="pt-3 text-xs text-zinc-400"><div className="flex justify-between gap-2"><span className="truncate">{photo.filename}</span>{photo.is_cover&&<span className="text-gold">CAPA</span>}</div>{photo.processing_status === 'done'&&!photo.is_cover&&<button type="button" onClick={()=>setCover(photo.id)} disabled={busy!==null} className="mt-3 border border-gold px-3 py-2 text-[10px] uppercase tracking-[0.12em] text-gold disabled:opacity-40">{busy===photo.id?'Salvando…':'Usar como capa'}</button>}</figcaption></figure>)}</div></section>;
}
